sudo: false
dist: xenial

language: ruby
cache: bundler
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master

script:
  - bundle exec chefstyle
